---
name: CI - Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./src/cloud/infrastructure

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4
          # CRED: https://app.terraform.io/app/settings/tokens
          # NAME: terraform-cloud-infrastructure
          # PREF: Kshzsh
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format Check
        id: fmt
        run: make fmt-check

      - name: Terraform Init
        id: init
        run: make init

      - name: Terraform Validate
        id: validate
        run: make validate

      - name: Terraform Plan
        id: plan
        run: make plan
